create table if not exists employee_info
(
	employee_id integer generated by default as identity,
	email varchar(50),
	password varchar(255),
	first_name varchar(50),
	last_name varchar(50),
	role varchar(20),
	primary key (employee_id)
);

create table if not exists product_item
(
	product_id integer generated by default as identity,
	product_name varchar(100),
	type varchar(20),
	is_seasonal boolean,
	is_available boolean,
	servings_remaining double precision,
	allergens varchar(200),
	display_icons integer,
	product_description varchar(300),
	premium_addition numeric(5,2),
	serving_size double precision,
	calories integer,
	saturated_fat integer,
	carbohydrate integer,
	protein integer,
	image varchar(200),
	is_premium boolean,
	quantity_in_cases integer,
	servings_per_case integer,
	cost_per_case double precision,
	primary key (product_id)
);

create table if not exists menu_item
(
	menu_item_id integer generated by default as identity,
	item_name varchar(50),
	max_entrees integer,
	max_sides integer,
	menu_item_base_price double precision,
	premium_multiplier integer,
	menu_item_description varchar(300),
	calories varchar(30),
	image varchar(200),
	primary key (menu_item_id)
);

create table if not exists "order"
(
	order_id integer generated by default as identity,
	order_date_time timestamp,
	employee_id integer not null,
	total_price numeric(7,2),
	primary key (order_id),
	foreign key (employee_id) references employee_info
);

create table if not exists order_menu_item
(
	order_menu_item_id integer generated by default as identity,
	order_id integer not null,
	menu_item_id integer not null,
	subtotal_price numeric(7,2),
	primary key (order_menu_item_id),
	foreign key (order_id) references "order",
	foreign key (menu_item_id) references menu_item
);

create table if not exists order_menu_item_product
(
	order_menu_item_product_id integer generated by default as identity,
	order_menu_item_id integer not null,
	product_id integer not null,
	primary key (order_menu_item_product_id),
	foreign key (order_menu_item_id) references order_menu_item,
	foreign key (product_id) references product_item
);

create table if not exists finances
(
	cash_balance double precision
);

create table if not exists customer_info
(
	customer_id integer generated by default as identity,
	email varchar(50),
	password varchar(255),
	first_name varchar(50),
	last_name varchar(50),
	beast_points integer,
	primary key (customer_id)
);