DROP TABLE IF EXISTS "order_menu_item_product" CASCADE;
DROP TABLE IF EXISTS "order_menu_item" CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS "menu_item" CASCADE;
DROP TABLE IF EXISTS "product_item" CASCADE;
DROP TABLE IF EXISTS "finances" CASCADE;
DROP TABLE IF EXISTS "customer_info" CASCADE;
DROP TABLE IF EXISTS "employee_info" CASCADE;