INSERT INTO product (product_id, product_name, type, base_price, is_premium, is_available, servings_remaining)
VALUES
(1, 'chowMein', 'side', 6.8, 'FALSE', 'TRUE', 50),
(2, 'friedRice', 'side', 6.8, 'FALSE', 'TRUE', 50),
(3, 'whiteSteamedRice', 'side', 6.8, 'FALSE', 'TRUE', 50),
(4, 'superGreensSide', 'side', 6.8, 'FALSE', 'TRUE', 50),
(5, 'theOriginalOrangeChicken', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(6, 'blackPepperSirloinSteak', 'entree', 1.5, 'TRUE', 'TRUE', 50),
(7, 'honeyWalnutShrimp', 'entree', 1.5, 'TRUE', 'TRUE', 50),
(8, 'grilledTeriyakiChicken', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(9, 'kungPaoChicken', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(10, 'honeySesameChickenBreast', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(11, 'beijingBeef', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(12, 'mushroomChicken', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(13, 'sweetfireChickenBreast', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(14, 'stringBeanChickenBreast', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(15, 'broccoliBeef', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(16, 'blackPepperChicken', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(17, 'superGreensEntree', 'entree', 1.5, 'FALSE', 'TRUE', 50),
(18, 'chickenEggRoll', 'appetizer', 2.0, 'FALSE', 'TRUE', 50),
(19, 'veggieSpringRoll', 'appetizer', 2.0, 'FALSE', 'TRUE', 50),
(20, 'creamCheeseRangoon', 'appetizer', 2.0, 'FALSE', 'TRUE', 50),
(21, 'applePieRoll', 'appetizer', 2.0, 'FALSE', 'TRUE', 50),
(22, 'fountainDrink', 'drink', 2.1, 'FALSE', 'TRUE', 50),
(23, 'aquafina', 'drink', 2.3, 'FALSE', 'TRUE', 50),
(24, 'gatorade', 'drink', 2.7, 'FALSE', 'TRUE', 50),
(200, 'misc', 'n/a', 0.0, 'FALSE', 'TRUE', 50);
