CREATE TABLE "employee" (
  "employee_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" Varchar(50),
  "last_name" Varchar(50),
  "role" Varchar(20)
);

CREATE TABLE "product" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" Varchar(100),
  "type" Varchar(20),
  "base_price" Decimal(5,2),
  "is_premium" Boolean,
  "is_available" Boolean,
  "servings_remaining" Float
);

CREATE TABLE "menu_item" (
  "menu_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "item_name" Varchar(50),
  "max_entrees" Int,
  "max_sides" Int,
  "is_unique" Boolean,
  "price_adjustment" Float,
  "premium_price_multiplier" Int,
  "side_price_adjustment" Float
);

CREATE TABLE "order" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_date_time" Timestamp,
  "employee_id" Int NOT NULL,
  "total_price" Decimal(7,2)
);

CREATE TABLE "order_menu_item" (
  "order_menu_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" Int NOT NULL,
  "menu_item_id" Int NOT NULL,
  "subtotal_price" Decimal(7,2)
);

CREATE TABLE "order_menu_item_product" (
  "order_menu_item_product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_menu_item_id" Int NOT NULL,
  "product_id" Int NOT NULL
);

CREATE TABLE "inventory_item" (
  "inventory_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" Int NOT NULL,
  "quantity_in_cases" Int,
  "servings_per_case" Int,
  "cost_per_case" Int,
  "inventory_item_name" Varchar(50)
);

ALTER TABLE "order" ADD FOREIGN KEY ("employee_id") REFERENCES "employee" ("employee_id");

ALTER TABLE "order_menu_item" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("order_id");

ALTER TABLE "order_menu_item" ADD FOREIGN KEY ("menu_item_id") REFERENCES "menu_item" ("menu_item_id");

ALTER TABLE "order_menu_item_product" ADD FOREIGN KEY ("order_menu_item_id") REFERENCES "order_menu_item" ("order_menu_item_id");

ALTER TABLE "order_menu_item_product" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id");

ALTER TABLE "inventory_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id");
