DROP TABLE IF EXISTS "order_menu_item_product" CASCADE;
DROP TABLE IF EXISTS "order_menu_item" CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS "menu_item" CASCADE;
DROP TABLE IF EXISTS "inventory_item" CASCADE;
DROP TABLE IF EXISTS "product" CASCADE;
DROP TABLE IF EXISTS "employee" CASCADE;